### ISSUE TITLE
Feature request: External script  support like xvdr for channel filtering. 

### ISSUE THREAD

**Issue by the-dreamer** [FernetMenta/vdr-plugin-vnsiserver#11]
Hello, 
currently iam using xvdr because earlier it was more stable on openelec x86_64 and raspberry pi and also faster. But it has not so much features as vnsi. Also the channel handling is a bit heavy with vnsi when you have 4 satelites with more than 4500 tv/radio channels. I have playing with vnsi and have got filtered the channels which i am interested in. Also i have a script written for xvdr which is doing nearly the same. But more for my needs. When i am comparing the solutions of boths i see some benefits in xvdr: it is filtering the channels on server side and the channel import is a lot faster because from the over 4500 channels it has filtered out a lot and "only" round about 1800 channels and epg data are imported. VNSI seems to filtering it on client side. All data is imported... and on a raspberrypi it is also slower therefore. Also a script is more flexible. For example i want new channels sorted into the last position of the group where it member of if.
I don't know how much work it would be to import this functionality, but as an option it would be great. Everyone could do what he wants. Handling it via GUI or via script. 

thanks

**Comment by FernetMenta** [comment]
vnsiserver filters on the server and only sends channels and EPG to the client which pass the filter. So far nobody mentioned that it would be slow. What is the spec of your server running vdr?

**Comment by the-dreamer** [comment]
Okay, so i am wrong. It is a AMD A4-5000 Quad-Core CPU with 8 gb ram and it is actually running openelec 5.0. It seems to load more channels maybe because the filter will let more channels export to kodi. I have edited the vnsi filter 3 months ago. So maybe it is now not up to date any more. I have tested vnsi last days because of some issues with kodi/vdr and saw a quite longer channel import. But this leads me to my initial request. I have edited the channels.conf once with an external tool for the groups and channel order. the script for xvdr is keeping the order and will sort out not visible (encrypted, which i have not subscribed) and also some sd channels, which has an HD version. This is not possible with vnsi and it takes much time to edit this all the time via the gui with thousands of channels. By time the channel list will growing with vnsi.

**Comment by FernetMenta** [comment]
vnsi does not grow the channel list by itself. channels are managed by vdr and you can used whatever method you like to edit channels.conf.

**Comment by the-dreamer** [comment]
No, i know that the vnsi will not grow the list by itself. But the TV Stations will change Bouquets, channel ids and also new channels will be added and i don't want to change this. There are many changes when you have 4 satelites. Vdr is continuously adding new transponder and channels. When vnsi has particular channels or groups not in the blacklist the list will grow and this seems to be happend in my system. That could be the reson for longer loading of epg and channels. 

So the idea of the channel filter is to do much work automatically. i don't have the time to edit the white/blacklist all the time or searching for new added channels at the end of the list somewhere between channel 1500 and 2200...  (for example 13th Street HD on Sky which was added in Autumn)

This ticket is only a request and i am not willing to fight for it. I think it would be a great feature, so vnsi could be usuable for me and maybe more people.

I had a dreambox before and the channel handling was much more confortable for me (main reason are the bouquets..). I sell it for some reasons and switch to xbmc. But one think i didn't saw before is, that the channel handling on the pvr/pc side is quite more complicated. TVheadend is a pain in the a** at all until now. Maybe they will change it. VDR needs more first time setup and has absolut no internal channel editor as backend. Okay a external editor did it. And xvdr is keep it clean when you have created a script. vnsi is able to edit the list via the gui but is quite inflexible.

So if you don't want this feature. It is okay. At least i only want to watch and record tv.

**Comment by FernetMenta** [comment]
I ask those question because I want to better understand the requirement. Could you elaborate on a scenario how this should work? What type of script? What calls the script? and so on.

**Comment by the-dreamer** [comment]
Okay, xvdr is callling a command, which you can add to the conf file (# ReorderCmd = group_channels.sh ) 
xvdr is calling this (i don't know at which time) and the script/program/shell get the channels in the stdin and have to output the channels to stdout. 

it doesn't matter what the destination is. It can be everything but has to process stdin and return the result to stdout. 

you can limit the channels.conf to 100 (interesting for rpi) channels or have a special order or filter out how you want. Only HD, only encrypted, only FTA, only Sky, only ARD, no Erotics ... that is the flexibililty you get. All this flavours is hardly to get into a gui. 

Based on this, if have written an awk script. New channels will be orderd at the end of a group instead at the end of the channel list for example. When RTL is starting a new channel for example "Super RTL Nitro 2" it will be automatically added it at the end of group RTL. When "Super RTL Nitro 2 HD" will be added, it will be discard because i didn't have subscripted HD+.  

Maybe an implemenation idea would be, if a external script is defined, internal (vnsi gui) is not used at all. 

here the peoples are takling about this: https://github.com/pipelka/vdr-plugin-xvdr/issues/115 just for clearification

**Comment by the-dreamer** [comment]
Due of dropping of XVDR support in Openelec such a feature would be nice. currently i am "filtering" the channels.conf before vdr is started but short after start the channel list is growing fast from ~2000 to over 4800 channels...  most not viewable channels... 
Is there any chance to get such a feature?

**Comment by the-dreamer** [comment]
actually the request can be closed. i am starting now a script based on the original one for my xvdr before vdr is started and create based on my needs the videoblacklist.vnsi. So i am able to sort the channels like i want and blacklisting the unwanted ones. 

may be one question is left: is vnsiserver using the blacklisting.vnsi file only once or everytime the channel list has changed? i am asking because i would like periodically execute my script and update the blacklist.vnsi.

**Comment by FernetMenta** [comment]
The black- and whitelist files are read on startup and after changing those lists. Is this ok for what you intend to do?

**Comment by the-dreamer** [comment]
i am using my script now since last week and it seems to work well. So these black- & whitelist is enough for me. Reordering of channels.conf is done before vdr is started. When i will move vdr to a server then the blacklisting will also work when my script is running once a day. For reordering channels vdr should be restarted by time. But i think this can be handled easily.

Kodi is showing now ~2000 channels of 4800 and i don't realy need to do any actions by hand. As i written before, my request can be closed.
