### ISSUE TITLE
slow switching times from sd to hd and vice versa on an Apple TV 4k

### ISSUE THREAD

**Issue by hoppel118** [FernetMenta/vdr-plugin-vnsiserver#114]
Hi guys,

some time ago I changed my Kodi client from an Nvidia Shield Android TV to an Apple TV 4k. On the Nvidia Shield I had really good switching times, like with all my kodi client hardware I ever had, regardless of switching between sd or hd.

But with the experimental Kodi version 17.6 with vnsiclient 2.6.25 for the Apple TV 4k from Memphiz, vdr 2.2.0 from the Debian Stretch repo and latest vnsiserver from GitHub I have slow (5 to 10 seconds) switching times while switching from an sd to an hd channel or vice versa. Switching between sd channels or switching between hd channels works as flawless within 1 or 2 seconds as I was used to with the Nvidia Shield and all my other clients (Windows 10, LibreELEC).

This issue is not related to latest vsniserver. It also happens with latest vnsiserver version 1.5.1 in the Debian Stretch repo and also with version 1.6.0 from GitHub. 

While updating the vnsiserver from v1.6.0 to v1.7.0 tonight, the issue was solved for the current kodi session. I did the following:

- start kodi 17.6, stop live tv
- stop vdr at my headless server
- update vnsiserver to latest git master version
- start vdr at my headless server
- start live tv

At this stage I had normal switching times (1 to 2 seconds) while switching between sd and hd or vice versa. After that I stopped kodi, restarted it and the slow switching times were back.

Kodi 17.6 for the Apple TV 4k is highly experimental and at the moment there is no kodi 18 for testing. 

Any thing we can do here? If so, which information do you need to have look at the issue?

Thanks and regards Hoppel

**Comment by hoppel118** [comment]
Ok, played a bit around. Activated a tvheadend docker, to see that it has the same problems. It's also the same with MrMC (Kodi fork) and VDR/TVHeadend.

But I recognized that it's much better without hardware acceleration activated at the Apple TV 4k.

So it's not a vdr/vnsi problem at all.

Thanks and regards Hoppel

**Comment by FernetMenta** [comment]
why do you waste money on crap like Apple TV? For the same price you can get a much better system.

hw decoder on Apple devices won't decode interlaced material. Hence useless for tv anyway.

**Comment by FernetMenta** [comment]
I do most of my development on a MacBook Pro. I also have an iPad and an iPhone. I know how those things work and would never ever use one of those devices as my primary box for watching tv. Android is even worse.

**Comment by hoppel118** [comment]
OK, I think you as a developer have another point of view.

The Nvidia Shield is working very good in combination with Kodi. The problem with the Nvidia Shield is the miss of automatic frame rate switching for Google PlayStore Apps like Netflix or Amazon Prime. Frame rate switching only works fine with Kodi. But you need Kodi 18 for these addons, which is unstable. It's the circle of hell. :)

Until Kodi 18 gets stable, boxes with LibreElec or CoreElec are not an option for me. Even if Kodi 18 gets stable, you have the danger to loose functionality of these kodi addons because of api changes. 

Do you use any of these streaming services? Which platform do you use for your daily Kodi TV?

Thanks and Regards Hoppel

**Comment by FernetMenta** [comment]
> Do you use any of these streaming services?

I have an Amazon Prime account.

> Which platform do you use for your daily Kodi TV?

I have an Intel system running Ubuntu with fluxbox as window manager. Means I run Kodi on X11 which I consider reference platform for video player.
