### ISSUE TITLE
VNSIServer re-injecting EIT info into stream which triggers PIN request on scrambled channels

### ISSUE THREAD

**Issue by Paulemann** [FernetMenta/vdr-plugin-vnsiserver#125]
Hey FernetMenta,

not sure if you're still working on this plugin. There is a discussion in the German vdr-forum and it seems that on scrambled channels VNSI server is reinjecting EIT info into the stream thus triggering a PIN request that was supposed to be suppressed by VDR hiding this EIT info to the CAM.

I have no detailed understanding of the related processes in VDR and VNSI Server and was hoping to  raise your attention to the post at [https://www.vdr-portal.de/forum/index.php?thread/132008-patch-cam-tweaks-f%C3%BCr-multi-channel-decryption/&postID=1322481#post1322481](url). 

The author proposes a seemingly harmless fix and I hope you would be able to validate his request and update VNSI server accordingly.

Thank you.

**Comment by FernetMenta** [comment]
Hi @Paulemann,

Right, I don't maintain this plugin anymore, VDR is dead end IMO. Not even a public repository where others can contribute in an acceptable way. 

I had a brief look into this topic. vnsiserver does inject nothing, it just requests pre-set PIDs form the receiver. If PID 18 is not desired it can be easily removed with DelPids right after this line:

https://github.com/FernetMenta/vdr-plugin-vnsiserver/blob/0b44ed82c6636d21b1b6e9156a142f38fb07e4a8/videoinput.c#L527

**Comment by Paulemann** [comment]
Hey @FernetMenta, 

thank you for your quick response and for looking into this request. Maybe some skilled programmer can pick up your proposal and apply the change - or even continue your work as a maintainer of this plugin.

Of course, I respect you decision to discontinue your work on vnsiserver and the kodi vnsi pvr addon but I also feel sad about it, since VDR is still relevant to a lot of people - including  myself. TVH just never gave me the sort of experience I had with VDR.

As I'm still gladly using this plugin and kodi addon, I thank you for creating those (and for still replying to requests ;) )

**Comment by FernetMenta** [comment]
np. Do you know how to compile the plugin? The fix is very simple. Just insert:
m_Receiver->DelPid(18);

after the line mentioned above.

**Comment by Paulemann** [comment]
Yes, I build all my addons and plugins as well as vdr and kodi. I will insert the extra line and re-build the plugin. Thanks for guiding me.
