### ISSUE TITLE
plugin is refreshing recordings only on kodi start/restart

### ISSUE THREAD

**Issue by uuzi** [FernetMenta/vdr-plugin-vnsiserver#14]
It would be nice to have the plugin refresh the available recordings every once in a while, since one of my kodi installs is running constantly (raspi 2), there is no way to refresh the recordings made with vdr itself (not via kodi) except to uplug power on the raspi and restart the whole thing.

**Comment by FernetMenta** [comment]
it triggers an update if the state of recordings changed. does this not work for you? set logging lever 3 for vdr. you should see the messages.

**Comment by uuzi** [comment]
it does trigger an update as i can see now in my syslog having enabled vdrs logging level 3
this is what happens in the log:
http://pastebin.com/T0PCgAU3

but kodi still does not see the new recording.

**Comment by FernetMenta** [comment]
do you have status messages enabled on the addon's settings dialog?

**Comment by uuzi** [comment]
no i have not

**Comment by FernetMenta** [comment]
trigger recordings update is one of those status messages you don't allow

**Comment by uuzi** [comment]
so this is a typical case of "problem exists between chair and keyboard"? :)

**Comment by FernetMenta** [comment]
hehe, does it work now? can we close this?

**Comment by uuzi** [comment]
works like a charm now thx
