### ISSUE TITLE
VNSI Server verweigert Mitarbeit

### ISSUE THREAD

**Issue by indigo12** [FernetMenta/vdr-plugin-vnsiserver#20]
Hallo FernetMenata ich habe deinen VNSI Server auf Debian im einsatz. Von einem Tag zum anderen hat er aufgehört zu funktionieren und produziert folgende Einträge im Syslog:

[4549] closing SVDRP connection
[4559] VNSI: Requesting clients to reload recordings list
[4559] VNSI: Recordings state changed (8333)
[4559] VNSI: Requesting clients to reload recordings list
[4559] VNSI: Recordings state changed (8334)
[4559] VNSI: Requesting clients to reload recordings list
[4559] VNSI: Recordings state changed (8335)
[4559] VNSI: Requesting clients to reload recordings list

Die Liste wird munter hochgezählt und im Kodi kann ich zwar die Kanalliste laden aber sobald ich einen Kanal auswehle passiert garnix, nicht mal eine Fehlermeldung.

**Comment by FernetMenta** [comment]
this is vdr 2.0.6 or lower,right?
it has a bug. I recommend that you upgrade. If was fixed in 2.1.2

**Comment by indigo12** [comment]
Ja es eine 2.0.3-1~etobi1 Installation, gibt es eine Lösung oder workaround ohne Update? Ich schreibe lieber Deutsch mein Englisch ist unterindisch :)

**Comment by e-tobi** [comment]
Die einfachste Lösung wäre wirklich ein Update. Für Jessie habe ich die aktuellen Pakete im Repository.

**Comment by indigo12** [comment]
Ok dabei habe ich nur 2 Probleme:
1. es ist eine Openmediavault Installation das die VDR als Plugin installiert hat. Keine Ahnung ob etwas dabei verändert wurde und wenn ja dann wie.
2. meine Linux kenntnisse sind nicht gerade berauschen - oder auch ich habe keine ahnung wie ich es machen soll.

**Comment by e-tobi** [comment]
Du kannst auch die VDR+Plugin-Pakete für Wheezy selber compilieren. Einfach den deb-src -Eintrag für die Jessie-Pakete hinzufügen und z.B. mit `apt-get --build source vdr` bauen und manuell via dpkg installieren.
