### ISSUE TITLE
Incorrect processing of Timer filenames

### ISSUE THREAD

**Issue by dave-p** [FernetMenta/vdr-plugin-vnsiserver#33]
According to man vdr(5), in the timers.conf file "If the name contains any ':' characters, these have to be replaced by '|'. If the name shall contain subdirectories, these have to be delimited by '~' (since the '/' character may be part of a regular programme name)."
The plugin does not replace ':' characters by '|', so if a timer is created which contains a colon (eg "New: Downton Abbey"), the filename becomes simply "New".

**Comment by FernetMenta** [comment]
thanks for bring this up. will look into it when I get time

**Comment by FernetMenta** [comment]
fixed by the referenced pr
