### ISSUE TITLE
Don't send "Shutting down in ..." to OSD over and over

### ISSUE THREAD

**Issue by simonbuehler** [FernetMenta/vdr-plugin-vnsiserver#39]
Hi,

with a low minuseractivity setting kodi shows a "VDR will shut down in ..." countdown every 10 seconds or so - and restarts it a over and over. As the user can't (and most probably doesn't want to) change anything about that, this message should be added to the ignored ones:

please add

https://github.com/FernetMenta/vdr-plugin-vnsiserver/blob/master/vnsiclient.c#L347
```
else if (strncmp(Message, trVDR("VDR will shut down in"), 21) == 0) return;
```
to fix this, thanks!

**Comment by FernetMenta** [comment]
ok, next time I touch this code I will add it. would be faster if you sent me a pull request :)
