### ISSUE TITLE
Aufnahmen während der Laufzeit von Kodi neu einlesen

### ISSUE THREAD

**Issue by privatscheiss** [FernetMenta/vdr-plugin-vnsiserver#45]
Ist es möglich die Aufnahmen Zeigesteuert neu einzulesen. Jedesmal Kodi neu starten ist nicht wirklich komfortabel! 

Gruß 
privatscheiss

**Comment by FernetMenta** [comment]
Jedesmal wenn sich die Aufnahmen von VDR ändern, wird ein Event an Kodi geschickt, dass das erledigt. Vorausgesetzt man hat diese Messages nicht deaktiviert.

**Comment by privatscheiss** [comment]
Danke war der Fehler mal wieder vor dem Bildschirm
