### ISSUE TITLE
timer -> inactive

### ISSUE THREAD

**Issue by lotan** [FernetMenta/vdr-plugin-vnsiserver#46]
Using the VNSI plugin, lately I had missed quite a few recordings, which is obviously quite annoying.

Looking into the vdr log shows messages of the pattern:
```
Mar 27 20:35:03 rsjlaa vdr[20036]: [20071] VNSI: Client with ID 12 connected: 127.0.0.1:37184
Mar 27 20:35:03 rsjlaa vdr[20036]: [3018] VNSI Client 12->127.0.0.1:37184 thread started (pid=20036, tid=3018, prio=high)
Mar 27 20:35:03 rsjlaa vdr[20036]: [3018] VNSI: Welcome client 'XBMC Media Center' with protocol version '8'
Mar 27 20:35:04 rsjlaa vdr[20036]: [20072] VNSI: Trigger EPG update for channel BBC NEWS, id: 2054409319
Mar 27 20:35:04 rsjlaa vdr[20036]: [20072] VNSI: Trigger EPG update for channel CBBC, id: 447096185
Mar 27 20:35:04 rsjlaa vdr[20036]: [20072] VNSI: Trigger EPG update for channel CBeebies, id: 471072513
Mar 27 20:35:04 rsjlaa vdr[20036]: [20072] VNSI: Trigger EPG update for channel BBC One Scot, id: 107324392
[...]
Mar 27 20:35:05 rsjlaa vdr[20036]: [20036] editing timer 2 (35 2158-2310 'The Night Manager')
[...]
Mar 27 20:35:14 rsjlaa vdr[20036]: [20036] timer 2 (35 2158-2310 'The Night Manager') modified (inactive)
[...]
Mar 27 20:35:14 rsjlaa vdr[20036]: [20072] VNSI: Timers state changed (14)
Mar 27 20:35:14 rsjlaa vdr[20036]: [20072] VNSI: Requesting clients to reload timers
```
I can't see any messages around that area that would explain the change of the timer to inactive.

I'm happy to look into other places if necessary.

**Comment by FernetMenta** [comment]
> Mar 27 20:35:05 rsjlaa vdr[20036]: [20036] editing timer 2 (35 2158-2310 'The Night Manager')

that's a message of VDR's timer menu. someone has modified the timer via vdr osd. from the timestamps you see that almost 10 secs later the state has changed. are you saying that nobody has accessed the timer menu?

**Comment by lotan** [comment]
No, no human operator anyway.

**Comment by FernetMenta** [comment]
do you use any other plugins or svdrsend scripts that could do this? vnsi does not access an interactive vdr menu. further this action has taken 10 secs. much too slow for an automated action. strange.

**Comment by lotan** [comment]
I completely understand your argument.

I played around again, obviously not being able to provoke a timer inactive message.
```
Mar 29 18:02:01 rsjlaa vdr[20036]: [20071] loading /etc/vdr/plugins/vnsiserver/allowed_hosts.conf
Mar 29 18:02:01 rsjlaa vdr[20036]: [20071] VNSI: Client with ID 21 connected: 127.0.0.1:56428
Mar 29 18:02:01 rsjlaa vdr[20036]: [14331] VNSI Client 21->127.0.0.1:56428 thread started (pid=20036, tid=14331, prio=high)
Mar 29 18:02:01 rsjlaa vdr[20036]: [14331] VNSI: Welcome client 'XBMC Media Center' with protocol version '8'
Mar 29 18:02:02 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:03 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:04 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:05 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:06 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:07 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:08 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:09 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:09 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:09 rsjlaa vdr[20036]: [20036] [softhddev]Flush: draw 1532x857+192+115 bm
Mar 29 18:02:10 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:11 rsjlaa vdr[20036]: [20036] [softhddev]Flush: level 0 active 1
Mar 29 18:02:11 rsjlaa vdr[20036]: [20036] editing timer 4 (35 2058-2140 'EastEnders')
```
This sequence is triggered by starting Kodi and picking "Live TV".

In my previous log excerpt, I stripped away [softhddevice] plugin messages as I thought it is noise. Now, I think it strange to have softhddevice messages in there at all as I didn't resume or do anything to it.

I'm not sure how to interpret this. But it seems to me the softhddev OSD (draw calls) is operated. I'm asking myself: Why would VNSI do anything to softhddev.
And if my interpretation is right, then it could do anything that is accessible through the OSD.

**Comment by lotan** [comment]
I apologize profoundly.

My problem has nothing to do with VNSI, it is an entirely different matter:

The softhddev plugin is reacting to lirc events while suspended.

The actual coincidence is that I use the remote control in VDR as well as Kodi.
So whatever buttons I pressed in Kodi ended up changing stuff in the softhddev menu.

Thank you for putting the time into this and reason it out.

**Comment by FernetMenta** [comment]
np, glad you solved it.
