### ISSUE TITLE
[RFE] Support for H265/HEVC streaming

### ISSUE THREAD

**Issue by hargut** [FernetMenta/vdr-plugin-vnsiserver#47]
Dear Rainer,

first of all, many thanks for your great development work on the PVR branch of Kodi & the VDR backend!
Currently 4k is coming up fast, and there are as well some (demo)-channels available on Astra 19.2E. Kodi already has H265/HVEC support, and VDR is also moving in that direction.

As it looks  like, the patch from Thomas Reufer, published on VDR-Portal.de is providing the HVEC parser for VDR which seems to work properly. Details can be found in this thread:
http://www.vdr-portal.de/board17-developer/board97-vdr-core/p1269333-rfc-h-265-frame-parser/

To successfully enable VNSI to stream 4k, it looks like it requires its own parser. It would be a great thing to have the PVR-Backend 4k streaming enabled.

Best regards,
Harald Gutmann

**Comment by FernetMenta** [comment]
This is on my list but other things have higher priority atm. With support of Intel GPUs for 10-bit this will get more interest.

**Comment by FernetMenta** [comment]
Almost done: https://github.com/FernetMenta/vdr-plugin-vnsiserver/pull/60

**Comment by FernetMenta** [comment]
hevc is now in master. I close this. thanks

**Comment by piotrasd** [comment]
sorry for write under closed ticket - can anyone can confirm this parser works ? i tried latest git version and on 4K channels im get only sound like Radio station, with Tvheadend no problem ...

**Comment by FernetMenta** [comment]
@papafelice has contributed this code. iirc he tested on dvb-t2 channels.

**Comment by hargut** [comment]
I've tested it on DVB-S2 Astra 19.2E 4k channels with success. Works smooth.
You just have to have vdr h265 enabled, with the patch mentioned in the 1st post of this thread.

**Comment by piotrasd** [comment]
> You just have to have vdr h265 enabled
 Some settings ? ok, patch was missing in my build i just added and compile, but i have problem now with channels. Even if i manual add to channels list i dont see them from Kodi side ... :(

**Comment by hargut** [comment]
No setting, just patch, compile & install properly. The hvec parser patch for vdr does not introduce any settings.

**Comment by piotrasd** [comment]
yes, everything working great ! thanks !
