### ISSUE TITLE
vnsiclient of kodi 16 (client specific menu -> error)

### ISSUE THREAD

**Issue by hoppel118** [FernetMenta/vdr-plugin-vnsiserver#48]
Hi FernetMenta,

I am on openmediavault 3.0.13 (debian jessie 8.4, 4.4.0-0.bpo.1-amd64) and use the plugins omv-vdr 3.0.2, omv-vdr-extras 3.0.1 and omv-vdr-vnsiserver 3.0.0 (v1.3.1). 

```
root@:~# vdr -V
vdr (2.0.3/2.0.0) - The Video Disk Recorder
epgsearchonly (0.0.1) - Direct access to epgsearch's search menu
epgsearch (1.0.1.beta3) - search the EPG for repeats and more
live (0.2.0) - Live Interactive VDR Environment
xineliboutput (1.1.0) - X11/xine-lib output plugin
quickepgsearch (0.0.1) - Quick search for broadcasts
conflictcheckonly (0.0.1) - Direct access to epgsearch's conflict check menu
streamdev-server (0.6.0-git) - VDR Streaming Server
vnsiserver (1.3.1) - VDR-Network-Streaming-Interface (VNSI) Server
```

As the frontend I use a windows 10 x64 (vnsiclient v1.11.14) machine with kodi 16.0 (with 16.1rc2 I have the same problem).

LiveTV works as expected, but when I try to open "system - tv - client specific - client specific settings" I get the following message.

**Error: Exception caught on main loop. Exiting**

In the following thread you find a screenshot of the error message:

http://www.vdr-portal.de/board60-linux/board62-software/board95-xbmc-kodi/p1270231-vdr-vdr-plugin-vnsiserver-kodi-kein-tv/#post1270231

Because of this it's not possible to configure the timeshift.

Where is the problem? 

Greetings Hoppel

**Comment by FernetMenta** [comment]
Kodi was ported from DX9 to DX11 but vnsi has catched up yet.  https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/72 fixes the crash. VDR OSD does not work on Windows until vnsi has been migrated to DX11.

**Comment by hoppel118** [comment]
Thanks for fixing the crash. But when do you think vnsi will be migrated to DX11? I can't estimate how much work it is.

**Comment by FernetMenta** [comment]
I don't know. I have never looked into DX11. I would appreciate if someone else than myself could do this because my list of todos is rather long.

**Comment by hoppel118** [comment]
With this I can't help. I am not a Developer. Only testing is possible for me.
