### ISSUE TITLE
vdr: message repeated 99 times: [ [1857] VNSI: close video input

### ISSUE THREAD

**Issue by jpg73** [FernetMenta/vdr-plugin-vnsiserver#49]
Dear FernetMenta, 
Let me share one issue I've
My config is ubuntu14.04+VDR2.2(same issue with 2.3.1)+VNSI1.10.10 + Kodi (15 or 16 or 17)
on HW side, TBS6991 +CAM + legal subscription
I define my list of channels(SD/HD : FTA or Scrambled) and works
The issue is the following, If I switch to a channels not covered by my subscription and come back after on official channel, the Zapping time is very high( up to 40sec instead of few secs)
and I've the following
Apr 15 22:19:54 streamy3 vdr: [1831] CAM 1: assigned to device 1
Apr 15 22:19:54 streamy3 vdr: [1831] VNSI: Successfully found following device: 0x955a20 (1) for receiving
Apr 15 22:19:54 streamy3 vdr: [1831] VNSI: Successfully switched to channel 7 - La2_h12721
Apr 15 22:19:54 streamy3 vdr: [1831] VNSI: Started streaming of channel La2_h12721 (timeout 10 seconds)
Apr 15 22:19:54 streamy3 vdr: [1855] device 1 receiver thread started (pid=1608, tid=1855, prio=high)
Apr 15 22:19:54 streamy3 vdr: [1857] cLiveStreamer stream processor thread started (pid=1608, tid=1857, prio=high)
Apr 15 22:19:54 streamy3 vdr: [1858] device 1 TS buffer thread started (pid=1608, tid=1858, prio=high)
Apr 15 22:19:55 streamy3 vdr: [1856] VNSI: VideoInput: no pat/pmt within timeout, falling back to channel pids
Apr 15 22:19:55 streamy3 vdr: [1856] VNSI: Video Input - new pmt, attaching receiver
Apr 15 22:19:55 streamy3 vdr: [1857] VNSI: Created stream for pid=552 and type=8
Apr 15 22:19:55 streamy3 vdr: [1857] VNSI: Created stream for pid=102 and type=2
Apr 15 22:19:55 streamy3 vdr: [1857] VNSI: Created stream for pid=52 and type=11
Apr 15 22:19:57 streamy3 vdr: [1629] frontend 0/0 lost lock on channel 7 (La2_h12721), tp 112721
Apr 15 22:19:58 streamy3 vdr: [1629] frontend 0/0 regained lock on channel 7 (La2_h12721), tp 112721
Apr 15 22:19:59 streamy3 vdr: [1855] detaching receiver - won't decrypt channel S19.2E-53-1119-12852 with CAM 1
Apr 15 22:19:59 streamy3 vdr: [1855] VNSI: call retune ...
Apr 15 22:19:59 streamy3 vdr: [1855] CAM 1: unassigned
Apr 15 22:19:59 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:19:59 streamy3 vdr: [1857] VNSI: call retune ...
Apr 15 22:19:59 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:19:59 streamy3 vdr: [1858] device 1 TS buffer thread ended (pid=1608, tid=1858)
Apr 15 22:19:59 streamy3 vdr: [1855] buffer stats: 18236 (0%) used
Apr 15 22:19:59 streamy3 vdr: [1855] device 1 receiver thread ended (pid=1608, tid=1855)
Apr 15 22:19:59 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:20:00 streamy3 vdr: message repeated 13 times: [ [1857] VNSI: close video input ...]
Apr 15 22:20:00 streamy3 vdr: [1629] frontend 0/0 lost lock on channel 7 (La2_h12721), tp 112721
Apr 15 22:20:00 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:20:01 streamy3 vdr: message repeated 8 times: [ [1857] VNSI: close video input ...]
Apr 15 22:20:01 streamy3 vdr: [1629] frontend 0/0 regained lock on channel 7 (La2_h12721), tp 112721
Apr 15 22:20:01 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:20:04 streamy3 vdr: message repeated 25 times: [ [1857] VNSI: close video input ...]
Apr 15 22:20:04 streamy3 vdr: [1857] VNSI: Channel: scrambled 3
Apr 15 22:20:04 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:20:14 streamy3 vdr: message repeated 99 times: [ [1857] VNSI: close video input ...]
Apr 15 22:20:14 streamy3 vdr: [1857] VNSI: Channel: no data 16
Apr 15 22:20:14 streamy3 vdr: [1857] VNSI: close video input ...
Apr 15 22:20:15 streamy3 vdr: message repeated 8 times: [ [1857] VNSI: close video input ...]
Apr 15 22:20:15 streamy3 vdr: [1857] CAM 1: assigned to device 1
Apr 15 22:20:15 streamy3 vdr: [1857] VNSI: Successfully found following device: 0x955a20 (1) for receiving
Apr 15 22:20:15 streamy3 vdr: [1865] device 1 receiver thread started (pid=1608, tid=1865, prio=high)
Apr 15 22:20:15 streamy3 vdr: [1867] device 1 TS buffer thread started (pid=1608, tid=1867, prio=high)
Apr 15 22:20:15 streamy3 vdr: [1630] VNSI: Video Input - new pmt, attaching receiver
[syslog.zip](https://github.com/FernetMenta/vdr-plugin-vnsiserver/files/222547/syslog.zip)

I guess it's an issue with VNSI (not the TBS driver or VDR) ... What did you advice ?

Thanks in advance
JP

**Comment by FernetMenta** [comment]
please set vdr logging level to 3 and pastebin log

**Comment by jpg73** [comment]
Hi, 
The attached syslog, is already with vdr -l 3 ... or maybe I miss something ?
Thanks
JP

**Comment by FernetMenta** [comment]
I hope you understand that I don't download logfiles.

**Comment by jpg73** [comment]
Hi, 
Sorry to contact you, but I didn’t understand what you request :-( (sorry I’m poor HW guy)
the VDR launched is already with -l 3 option (vdr -l 3 -d -P live -P xmltv2vdr -P vnsiserver -v /recordings -c /tmp/datas_buffer/vdr -E /tmp/datas_buffer/epg --chartab=ISO-8859-15 --user=vdr)

I put zipped file of syslog in the git (because not allowed to put syslog file alone)
I pasted last sentences of this syslog in the git…

Thanks in advance for your help
JP

**Comment by meier2meier** [comment]
Hi JP!

Have a look at http://pastebin.com.

Br

> Am 17.04.2016 um 11:25 schrieb jpg73 <notifications@github.com>:
> 
> Hi, 
> Sorry to contact you, but I didn’t understand what you request :-( (sorry I’m poor HW guy)
> the VDR launched is already with -l 3 option (vdr -l 3 -d -P live -P xmltv2vdr -P vnsiserver -v /recordings -c /tmp/datas_buffer/vdr -E /tmp/datas_buffer/epg --chartab=ISO-8859-15 --user=vdr)
> 
> I put zipped file of syslog in the git (because not allowed to put syslog file alone)
> I pasted last sentences of this syslog in the git…
> 
> Thanks in advance for your help
> JP
> 
>

**Comment by jpg73** [comment]
Thanks a lot

http://pastebin.com/bhKAPHZh

I hope it's done in the correct way
Again Apologies for my poor knowledge

**Comment by FernetMenta** [comment]
please comment on the scenario. how should I know what channels are covered by your subscription and what are not. what did you do when recording the log? what did you observe? what did you expect to happen?

**Comment by jpg73** [comment]
Hi, 
First of all , thank for your patience about this issue
scenario is extracted from a complex one, but with this the bug is perfectly reproduced
1/ VDR freshly rebooted
2/ Kodi launched on PC
3/ start to tune Q_11185 channel which is not supported by my subscription
- Kodi informs channels is scrambled -> OK
4/ after roughly 10sec , I tune to other channel La2_h12721 .Which is supported by my subs.
5/ in this sequence , Kodi takes from 30 -50sec to show the descramble the movie (in stead of 2-3sec)

In the opposite, when I switch from/to any channels handled by subscription.I didn't observe any issue.

Thanks in advance
JP

**Comment by FernetMenta** [comment]
VDR is a bit nasty in this regard. Is has a hard set scrambling timeout that disconnects the receiver after only 3 sec if no descrambled packets arrives within this time. VNSI can only try to retune. I can try some tweaks. Are you able to compile from source?

**Comment by jpg73** [comment]
'sure 
VDR 2.3.0 +VNSI was tried with your advices founded on web!

**Comment by FernetMenta** [comment]
could you try branch "test" https://github.com/FernetMenta/vdr-plugin-vnsiserver/tree/test
there is a new setting "DisableScrambleTimeout". Set this to true

**Comment by jpg73** [comment]
compile OK ! but is a compilation setting ? or some option to launch with vdr -l 3 -d -P live -P vnsiserver ... ?? 
Thanks

**Comment by FernetMenta** [comment]
> vnsiserver.DisableScrambleTimeout

yes, but much easier with VDR UI. You can a bring up VDR ui for configuration in Kodi with settings->tv->client specific. navigate to vdr setup->plugins and you'll find this new setting.

**Comment by jpg73** [comment]
Hi, 
your setting remove  "VNSI: close video input" message , but 
now I've a lot of ... 
Apr 17 22:17:43 streamy3 vdr: [1893] VNSI: Channel: no data 16
Apr 17 22:17:53 streamy3 vdr: [1893] VNSI: Channel: no data 16

then to summary now, 
1/If I switch to "channel 1"not supported by my subs
2/the first next "channel2" (handled by my subscription) generate a no data 16
3/the second, unlock totally the situation ... and perfectly descramble a "channel3"
The crispy story ... if I go back on "channel2" ... no problem at all :-(

It's obvious it's not a VNSI issue ... what did you advice ? driver Issue or VDR issue ?
Thanks
JP

**Comment by FernetMenta** [comment]
please pastebin a log and comment on the scenario.

**Comment by jpg73** [comment]
Hi,  
Here is the pastebin http://pastebin.com/QJ0ff7R6
About the scenario
1/ fresh boot up
2/ launch VDR2.3 +VNSI with DisableScrambleTimeout set to true
3/ launch KODI and select La2_h12721
4/ Select Fr3_h11681HOTB -> Perfectly descrambled
5/ Select Q_11185_KO (which is not handled by my subscription)
6/ Select La2_h12721 -> Kodi refuse to descramble  (with supported by my subscription
7/ Select Fr3_h11681HOTB -> Perfectly descrambled
8/ Select La2_h12721 -> and ... it works !!!

Where did you think the issue comes ? VNSI ? VDR ? TBS Drivers ?

Thanks again for your envolvment
JP

**Comment by FernetMenta** [comment]
did 3/ result in success?

**Comment by jpg73** [comment]
it's strange, the first zap , is always not perfect.Let 's say NO
Regards
JP

**Comment by FernetMenta** [comment]
that's really strange because the log shows no issues for first zap. I would have expected logs like "scrambled" or "no data" but there is nothing like this after:
Apr 18 20:40:52 streamy3 vdr: [1845] VNSI: Video Input - new pmt, attaching receiver

Could you pastebin kodi.log for this scenario? 

Either I do something wrong or scrambled data passes through.

**Comment by jpg73** [comment]
I replay all for perfect alignement between each logs
Scenario still the same
Kodi Log : http://pastebin.com/0frwc4P2
Server Log : http://pastebin.com/u82LJkrh

THX a lot

**Comment by FernetMenta** [comment]
> Apr 18 22:20:53 streamy3 vdr: [1819] ERROR: unknown config parameter: vnsiserver.DisableScrambleTimeout = 1

I am wondering if you compiled the correct branch. Do you see this new parameter in the VDR UI?

**Comment by jpg73** [comment]
Oh yes, 1/I try first to set in setup.conf

But seems not taken into account by VDR

2/ Now I saw this param in VDR UI & it’s set to true

(did you need snapshot ?)

Regards

JP

**Comment by FernetMenta** [comment]
I forced pushed an update to branch test (reset --hard). Please run the scenario again and pastebin syslog and kodi.log

**Comment by jpg73** [comment]
Hi , I’m lost, what ’s to do ? git update ? & new compilation ?
Thanks

**Comment by FernetMenta** [comment]
Get the new version from branch "test", and compile it. I squashed some changes. Means if you normally do "git pull", that won't work. This requires "get fetch" and "git reset --hard".

**Comment by jpg73** [comment]
Here is the logs ...
Kodi : http://pastebin.com/eZTZknea
Syslog: http://pastebin.com/5NwKJzgp
Same scenario
Thanks

**Comment by FernetMenta** [comment]
Sorry, I did a mistake and the config parameter was not parsed properly. I update branch test. Could you try again please.

**Comment by jpg73** [comment]
I'm glad to see, I'm not alone creating mistakes ;-)
Here are logs
Kodi : http://pastebin.com/TKTeCwH6
Syslog : http://pastebin.com/LZnyUnDU
Same Scenario, but at step 3 & 6, instead of "black screen" with descrambled channel. I see degraded channels (lot of Big pixel) BUT again step 4,7,8 work perfectly !
Thanks

**Comment by FernetMenta** [comment]
I have changed logging messages and this makes me sure that you are not running latest version of my branch "test"
https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/0b0e26f877681ea5ce6fd8b7541f34af1ac2a49a

**Comment by jpg73** [comment]
Could you tell me , what  Ive to do more ?
root@streamy3p:/home/jp/vdr23/vdr-plugin-vnsiserver# git pull
Auto-merging videoinput.c
CONFLICT (content): Merge conflict in videoinput.c
Automatic merge failed; fix conflicts and then commit the result.
root@streamy3p:/home/jp/vdr23/vdr-plugin-vnsiserver# git fetch
root@streamy3p:/home/jp/vdr23/vdr-plugin-vnsiserver# git reset --hard
HEAD is now at d30bbaf bump version to 1.4.0

**Comment by FernetMenta** [comment]
This is why I mentioned that "git pull" won't work. I never use this command and would vote to ban it from the planet :)
I assume you have only a single remote repo that points to this one here. Verify with:
git remote -v
In general this repo is named "origin". do
git fetch origin
git reset --hard origin/test

the last command sets your current branch to be equal to my branch "test"

**Comment by jpg73** [comment]
root@streamy3p:/home/jp/vdr23/vdr-plugin-vnsiserver# git remote -v
origin	https://github.com/FernetMenta/vdr-plugin-vnsiserver (fetch)
origin	https://github.com/FernetMenta/vdr-plugin-vnsiserver (push)
root@streamy3p:/home/jp/vdr23/vdr-plugin-vnsiserver# git fetch origin
root@streamy3p:/home/jp/vdr23/vdr-plugin-vnsiserver# git reset --hard origin/test
HEAD is now at 73069e0 squash me

Is it OK , with this ? ready to compile ?Thanks

**Comment by FernetMenta** [comment]
this looks good

**Comment by jpg73** [comment]
Here is ...
Kodilog : http://pastebin.com/k6rshbya
Syslog : http://pastebin.com/b7C6t6Rm

Same Scenario, but at step  6, instead of "black screen" with descrambled channe info l. I see degraded channels (lot of Big pixel) BUT again step 4,7,8 work perfectly ! Now Step 3 is OK ... 
Thanks

**Comment by FernetMenta** [comment]
could you try setting PMT timeout to 5 sec?

**Comment by jpg73** [comment]
no significant changes , let's say it's worst with PMT=5 (instead of PMT=1)
:-(

**Comment by jpg73** [comment]
I feel we are not so far to the solution, Is there any other parameter to check on VDR level ?

**Comment by jpg73** [comment]
I ve feeling some channels "block" then CAM and some channels "unlock" the situation ...

**Comment by jpg73** [comment]
Smal observation, FOR La2_h12721 the exact frequency is 12721.75 and  Fr3_11681 the exact frequency is 11681 .Then the same
If I try to defineLa2_h12721 with frequency of 12722 ... the result is worst than with frequency of 12721.
Is there a way define the exact frequency ? How VDR round it ?
Thanks
JP

**Comment by FernetMenta** [comment]
Could you please post a log with pmt timeout > 5

**Comment by jpg73** [comment]
with PMT=8
Logs are
Kodi:http://pastebin.com/rGFmXZr1
Server: http://pastebin.com/pMi6kHxD
Same scenario, same observations

X10 thanks

**Comment by FernetMenta** [comment]
The log looks fine. VDR thinks the stream gets descrambled because the scramble flag is reset. Then the still scrambled stream produces lots of decoder error in Kodi. My guess is that the CAM does something wrong. What happens if you press stop after 5 and then start La2_h12721?

**Comment by jpg73** [comment]
If I stop after 5 and start on LA2 , produced the same than step 3 ... not perfectly descrambled (big pixels or image partially green)

**Comment by FernetMenta** [comment]
now I am confused:

> Now Step 3 is OK ... 

you said step 3 was ok? Is it ok or not?

**Comment by jpg73** [comment]
result for step 3 vary from PMT ( bad with PMT=8 & PMT=5) -> not perfectly descrambled (big pixels or image partially green)
With PMT=1 : it is the same but after 20-30 sec, the image becomes clear (without any action)

**Comment by FernetMenta** [comment]
I am not in the mood to give up :)
Could you please try the new version I pushed to branch test.

**Comment by jpg73** [comment]
no changes :-( 
logs are(for PMT=1)
Kodi : http://pastebin.com/nmTZacVw
Server : http://pastebin.com/pqpbU6Tw
I think you have to continue in this direction ... I believe in you
Best...

**Comment by FernetMenta** [comment]
how is the first switch now?

**Comment by jpg73** [comment]
bad ... totally unreadable :-(

**Comment by FernetMenta** [comment]
please do another run with the new parameter "disablescrambletimeout" disabled. also make sure that priority (vnsi config setting in kodi) is set to 0. then we get the same sequence of action as vdr does when it starts a recording.

**Comment by jpg73** [comment]
With disable = 0 & priority = 0 
Kodi: http://pastebin.com/ChjqeH75
Server : http://pastebin.com/byu2vU65
STEP 3 is OK ... now :-)
for Step 6 ... we are close to a solution , when I start La2 , it's perfectly descrambled and after few second, -> image becomes bad -> and msg appear channel scrambled
again I need to switch on Fr3 (Step7) to unlock the situation
Regards

**Comment by FernetMenta** [comment]
what happen if you press stop before step 6?

**Comment by jpg73** [comment]
exactly same than step6
 it's perfectly descrambled and after few second, -> image becomes bad -> and msg appear channel scrambled...
seems issues linked

**Comment by FernetMenta** [comment]
that's strange because stop resets the state. from vnsi or pvr point of view it should exactly behave as step 3.

**Comment by jpg73** [comment]
Hi, Sorry for the late fdck ( I was on BTrip last week)
I try several test case , and It's obvious first start and stop/start doesn't produce the same result
Did you advice VDR or Driver issue?
Thanks

**Comment by jpg73** [comment]
Hi, 
After deep investigation, I found interesting topic
I'm using TBS6991SE -> 2DVBS IN & 2CAM
If I connect both TBS inputs on LNB -> no issues at all !
Regards

**Comment by FernetMenta** [comment]
Interesting. Seems the cam waits for some signal from the unconnected DVB input.

**Comment by jpg73** [comment]
Ive tested vdr -l 3 -d -D 0 -P vnsiserver (to specify the use of only device 0) but issues are observed
Did you have idea how to manually remove /dev/dvb/adapter1 ? 
regards

**Comment by FernetMenta** [comment]
I never tried a dual tuner card myself. What issues do you observe with those parameters? Does it not work at all?

**Comment by jpg73** [comment]
if the 2 inputs are connected to LNB , it works perfectly
If only 1 connected, I ve the above issue

could you check ... http://pastebin.com/N4ScR83g
Thanks
JP

**Comment by FernetMenta** [comment]
This is a private paste, I can't access it

**Comment by jpg73** [comment]
Try again …

**Comment by FernetMenta** [comment]
this was solved offline
