### ISSUE TITLE
SIGABRT error

### ISSUE THREAD

**Issue by MichaelAnders** [FernetMenta/vdr-plugin-vnsiserver#5]
Hi,

VDR 2.0.6 with git code of VNSI plugin. Switching a channel resulted in this crash (using gdb and then doing 'bt') - doesn't happen often, only sometimes. Not sure what other data could be of use.

vdr: malloc.c:4294: malloc_consolidate: Assertion `nextchunk->fd_nextsize->bk_nextsize == nextchunk' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffa2ffd700 (LWP 1231)]
0x00007ffff62ee4f5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff62ee4f5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff62f1c5b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff633622d in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff633711e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff6338566 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff633b0b5 in malloc () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff6c3fded in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff30bef2b in cVNSIClient::StartChannelStreaming (this=0x7fffa4005030, channel=0x89a400, priority=0, timeshift=1 '\001', timeout=10) at vnsiclient.c:168
#8  0x00007ffff30bfb54 in cVNSIClient::processChannelStream_Open (this=0x7fffa4005030) at vnsiclient.c:764
#9  0x00007ffff30c4fc2 in cVNSIClient::processRequest (this=0x7fffa4005030, req=<optimized out>) at vnsiclient.c:425
#10 0x00007ffff30c52b4 in cVNSIClient::Action (this=0x7fffa4005030) at vnsiclient.c:145
#11 0x00000000004ffb4d in cThread::StartThread (Thread=0x7fffa4005030) at thread.c:262
#12 0x00007ffff7974e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0*

**Comment by FernetMenta** [comment]
I think this can be closed now. If the issue still exists, please open a new issue.
