### ISSUE TITLE
demuxer.c:628]: (style) Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [FernetMenta/vdr-plugin-vnsiserver#50]
demuxer.c:628]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

  while (len = m_VideoBuffer->Read(&buf, TS_SIZE, m_endTime, m_wrapTime) == TS_SIZE)

Maybe better code

  while ((len = m_VideoBuffer->Read(&buf, TS_SIZE, m_endTime, m_wrapTime)) == TS_SIZE)

**Comment by FernetMenta** [comment]
Thanks, I will correct this soon.

**Comment by FernetMenta** [comment]
fixed in master now. thanks
