### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by farazcom** [FernetMenta/vdr-plugin-vnsiserver#54]
hi please help me please i run this command in xbmc 
   $ git clone https://github.com/FernetMenta/vdr-plugin-vnsiserver
   $ cd vdr-plugin-vnsiserver
   $ make
   $ sudo make install

but this error show me:
in file include from vnsiclient.c :26:0:
vnsiclient.h :87 :16 error virtical  void cvnsiclient : :channelchange(const cchannel*) ' marked override but dos not override 
virtical  void cvnsiclient : :channelchange(const cchannel  * channel ) ' override
makefile : 86:recipe for target 'vnsiclient.o'  failed 
make : *** [vnsiclient.o] error 1

 please help

**Comment by Gilles76** [comment]
Hi,
I'm using vdr 2.03 source, and I've got the same error even if there are previous correction un source code.
Best regards

**Comment by FernetMenta** [comment]
should be fixed now

**Comment by Gilles76** [comment]
Hi, 
Thank you for your fix but it's not working for me. Here is the error:
`
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -std=c++11 -c -D_GNU_SOURCE -DPLUGIN_NAME_I18N='"vnsiserver"' -DVNSI_SERVER_VERSION='"1.5.0"' -I/usr/local/src/vdr-2.0.3/include -o videobuffer.o videobuffer.c
In file included from videobuffer.h:29:0,
                 from videobuffer.c:25:
videobuffer.c: In member function ‘virtual bool cVideoBufferRAM::Init()’:
/usr/local/src/vdr-2.0.3/include/vdr/tools.h:35:75: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘off_t {aka long long int}’ [-Wformat=]
 #define isyslog(a...) void( (SysLogLevel > 1) ? syslog_with_tid(LOG_ERR, a) : void() )
                                                                           ^
config.h:48:23: note: in expansion of macro ‘isyslog’
 #define INFOLOG(x...) isyslog("VNSI: " x)
                       ^
videobuffer.c:219:3: note: in expansion of macro ‘INFOLOG’
   INFOLOG("allocated timeshift buffer with size: %ld", m_BufferSize);
   ^
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -std=c++11 -c -D_GNU_SOURCE -DPLUGIN_NAME_I18N='"vnsiserver"' -DVNSI_SERVER_VERSION='"1.5.0"' -I/usr/local/src/vdr-2.0.3/include -o videoinput.o videoinput.c
videoinput.c: In member function ‘virtual void cLivePatFilter::Process(u_short, u_char, const u_char*, int)’:
videoinput.c:202:17: warning: variable ‘ProcessCaDescriptors’ set but not used [-Wunused-but-set-variable]
            bool ProcessCaDescriptors = false;
                 ^
videoinput.c: In member function ‘bool cVideoInput::Open(const cChannel*, int, cVideoBuffer*)’:
videoinput.c:462:21: error: ‘class cLiveReceiver’ has no member named ‘SetPriority’
         m_Receiver->SetPriority(MINPRIORITY);
                     ^
videoinput.c:467:21: error: ‘class cLiveReceiver’ has no member named ‘SetPriority’
         m_Receiver->SetPriority(m_Priority);
                     ^
Makefile:86: recipe for target 'videoinput.o' failed
make[1]: *** [videoinput.o] Error 1

*** failed plugins: vnsiserver

Makefile:201: recipe for target 'plugins' failed
make: *** [plugins] Error 1

`

Hope that helps.

Best Regards.

Gilles.

**Comment by FernetMenta** [comment]
I pushed another fix
btw: why do you use such an outdated version of vdr?

**Comment by Gilles76** [comment]
Thank you very much for your fix it's ok.

I know this isn't a new version, but it's easier for me (for the moment) to maintain a vdr from debian package. Previously, I test a compil 2.2 version and add problem with epg.
To sum up, I absolutly need a working vdr for a friend and will try 2.2 version for me.

Just one more thing. A huge thank you for what you are doing with vnsi and kodi.

Thanks again.

Gilles.

**Comment by FernetMenta** [comment]
Thank you too

**Comment by w3techie** [comment]
So, I am doing this on a Raspberry Pi within OSMC after failing to setup a Raspbian Lite with a headless VDR with a PVR backend for channels. I get this same sort of error compiling this on Debian:

Makefile:86: recipe for target 'videoinput.o' failed
make[1]: *_* [videoinput.o] Error 1

After doing all kinds of system hardening by installing packages and building dependencies I thought would help the compiler resolve this issue alone, I went into the Makefile and found there is actually an OBJS= line where you can edit the files used by the compiler. I notice that while there is a videoinput.h and videoinput.c there is no videoinput.o file. I copied with git clone. So, I added the two videoinput files that were there, and removed the videoinput.o file that is not there. After that it finished compiling, but that still does not mean I got it working. For some reason I cannot simply install this plugin from the terminal using apt-get either, even though I think I have the right PPA.
