### ISSUE TITLE
long switch times on scrambled channels

### ISSUE THREAD

**Issue by Karl-opec** [FernetMenta/vdr-plugin-vnsiserver#57]
I had to revert the commit "reset parsers if stream is scrambled" (ID 51a0882)  for my vdr-2.2.0 because it leads to long channel switching times (more  than 12 sec) for scrambled channels.

On the client, a pop up window "channel is scrambled" is shown, but the the stream is working normal.

After reverting the commit everything works as expected and smooth.

**Comment by FernetMenta** [comment]
please try branch cam. should also compile for vdr < 3.2.1

**Comment by Karl-opec** [comment]
branch cam seams to work so far. Thanks!

**Comment by FernetMenta** [comment]
Thanks for feedback. Don't hesitate to report any issues, even minors.

**Comment by Karl-opec** [comment]
At the server logs I get continues messages like this:

[code]
Jun 27 10:33:54 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel MDR Thüringen, id: 1545991952
Jun 27 10:34:08 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel MDR Thüringen, id: 1545991952
Jun 27 10:34:20 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel MDR Thüringen, id: 1545991952
Jun 27 10:34:32 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel SWR Fernsehen RP, id: 723699590
Jun 27 10:34:43 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel SWR Fernsehen RP, id: 723699590
Jun 27 10:34:55 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel SWR Fernsehen RP, id: 723699590
Jun 27 10:35:08 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel SWR Fernsehen RP, id: 723699590
Jun 27 10:35:20 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR Funkhaus Europa, id: 785793115
Jun 27 10:35:32 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR Funkhaus Europa, id: 785793115
Jun 27 10:35:43 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR Funkhaus Europa, id: 785793115
Jun 27 10:35:54 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR Funkhaus Europa, id: 785793115
Jun 27 10:36:09 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 4, id: 664130726
Jun 27 10:36:23 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 4, id: 664130726
Jun 27 10:36:34 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 4, id: 664130726
Jun 27 10:36:48 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 4, id: 664130726
Jun 27 10:37:00 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 5, id: 1351803952
Jun 27 10:37:13 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 5, id: 1351803952
Jun 27 10:37:25 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 5, id: 1351803952
Jun 27 10:37:36 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 5, id: 1351803952
Jun 27 10:37:48 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 2, id: 1076754849
Jun 27 10:38:00 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 2, id: 1076754849
Jun 27 10:38:11 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 2, id: 1076754849
Jun 27 10:38:23 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel WDR 2, id: 1076754849
Jun 27 10:38:35 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel 1LIVE, id: 1495574555
Jun 27 10:38:48 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel 1LIVE, id: 1495574555
Jun 27 10:38:59 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel 1LIVE, id: 1495574555
Jun 27 10:39:13 vnas vdr[5352]: [5383] VNSI: Trigger EPG update for channel 1LIVE, id: 1495574555
[/code]

Is it possible to disable that?

**Comment by FernetMenta** [comment]
lower the logging level of vdr to 1.

**Comment by Karl-opec** [comment]
I tried branch cam now for several days. The following observation i need to mention:
After switching several channels (scrambled, non scrambled) it gets impossible to watch unscrambled channels. Switching scrambled channels still works then. After switching timeout 
the message (vnsi no data) is shown.

Perhaps you have an idea?

I get back to the master branch with reverted commit 51a0882.

**Comment by FernetMenta** [comment]
Mind trying the updated branch cam? Make sure to set priority (vnsi settings in Kodi) NOT to -1

**Comment by Karl-opec** [comment]
I have tried it. Seams to work. I will watch and report.
My vnsi  priority setting is 0 (zero). and vnsiserver setting : disable scramble output is no

thanks

**Comment by Karl-opec** [comment]
There seams to be an issue with channel SUPER RTL HD from astra.
vdr tunes to channel descrambling is started, a key is found but no stream starts.

[code]
Jun 29 12:53:53 vnas vdr[5799]: [10517] VNSI: Successfully switched to channel 12 - VOX HD
Jun 29 12:53:53 vnas vdr[5799]: [10517] VNSI: Started streaming of channel VOX HD (timeout 14 seconds)
Jun 29 12:53:53 vnas vdr[5799]: [14640] VNSI: Created stream for pid=511 and type=8
Jun 29 12:53:53 vnas vdr[5799]: [14640] VNSI: Created stream for pid=515 and type=1
Jun 29 12:53:53 vnas vdr[5799]: [14640] VNSI: Created stream for pid=49 and type=9
Jun 29 12:53:53 vnas vdr[5799]: [14640] VNSI: Created stream for pid=33 and type=11
Jun 29 12:53:54 vnas vdr[5799]: [14640] VNSI-Error: cParser::AddPESPacket - max buffer size reached, pid: 511
Jun 29 12:53:54 vnas vdr[5799]: [14640] VNSI: Audio stream change, pid: 515, channels: 2, samplerate: 48000
Jun 29 12:53:54 vnas vdr[5799]: [5837] VNSI: Trigger EPG update for channel WDR HD Düsseldorf, id: 2039157986
Jun 29 12:53:55 vnas vdr[5799]: [14640] VNSI: Video stream change, pid: 511, width: 1920, height: 1080, aspect: 1,777778
Jun 29 12:54:04 vnas vdr[5799]: [14640] VNSI: exit streamer thread
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: LiveStreamer::Close - close
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: close video input ...
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: activate live receiver: 0, pmt change: 0
Jun 29 12:54:04 vnas vdr[5799]: [10517] DVBAPI: 3.0 set CAM decrypt (SID 61201 (0xEF11), caLm 5, HasCaDescriptors 1)
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: close video input ...
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: LiveStreamer::Close - close
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: close video input ...
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: Successfully found following device: 0x1c9bfc0 (4) for receiving
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: activate live receiver: 1, pmt change: 1
Jun 29 12:54:04 vnas vdr[5799]: [10517] DVBAPI: 3.0 set CAM decrypt (SID 11931 (0x2E9B), caLm 4, HasCaDescriptors 1)
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: Successfully switched to channel 14 - SUPER RTL HD
Jun 29 12:54:04 vnas vdr[5799]: [10517] VNSI: Started streaming of channel SUPER RTL HD (timeout 14 seconds)
Jun 29 12:54:04 vnas vdr[5799]: [14714] VNSI: Created stream for pid=300 and type=8
Jun 29 12:54:04 vnas vdr[5799]: [14714] VNSI: Created stream for pid=310 and type=1
Jun 29 12:54:04 vnas vdr[5799]: [14714] VNSI: Created stream for pid=330 and type=9
Jun 29 12:54:04 vnas vdr[5799]: [14714] VNSI: Created stream for pid=320 and type=11
Jun 29 12:54:05 vnas vdr[5799]: [14714] VNSI: Audio stream change, pid: 310, channels: 2, samplerate: 48000
Jun 29 12:54:05 vnas vdr[5799]: [5837] VNSI: Trigger EPG update for channel WDR HD Essen, id: 244065396
Jun 29 12:54:06 vnas vdr[5799]: [14714] VNSI: Video stream change, pid: 300, width: 1920, height: 1080, aspect: 1,777778
Jun 29 12:54:06 vnas vdr[5799]: [14714] VNSI: CAM error, try reset
Jun 29 12:54:06 vnas vdr[5799]: [14714] VNSI: close video input ...
Jun 29 12:54:06 vnas vdr[5799]: [14714] VNSI: activate live receiver: 0, pmt change: 0
Jun 29 12:54:06 vnas vdr[5799]: [14714] VNSI: Successfully found following device: 0x1c9bfc0 (4) for receiving
Jun 29 12:54:06 vnas vdr[5799]: [14714] VNSI: activate live receiver: 1, pmt change: 1
Jun 29 12:54:06 vnas vdr[5799]: [14714] DVBAPI: 3.0 set CAM decrypt (SID 11931 (0x2E9B), caLm 4, HasCaDescriptors 1)
Jun 29 12:54:08 vnas vdr[5799]: [14714] VNSI: CAM error, try reset
Jun 29 12:54:08 vnas vdr[5799]: [14714] VNSI: close video input ...
Jun 29 12:54:08 vnas vdr[5799]: [14714] VNSI: activate live receiver: 0, pmt change: 0
Jun 29 12:54:08 vnas vdr[5799]: [14714] VNSI: Successfully found following device: 0x1c9bfc0 (4) for receiving
Jun 29 12:54:08 vnas vdr[5799]: [14714] VNSI: activate live receiver: 1, pmt change: 1
Jun 29 12:54:08 vnas vdr[5799]: [14714] DVBAPI: 3.0 set CAM decrypt (SID 11931 (0x2E9B), caLm 4, HasCaDescriptors 1)
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: CAM error, try reset
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: close video input ...
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: activate live receiver: 0, pmt change: 0
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: Successfully found following device: 0x1c9bfc0 (4) for receiving
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: activate live receiver: 1, pmt change: 1
Jun 29 12:54:09 vnas vdr[5799]: [14714] DVBAPI: 3.0 set CAM decrypt (SID 11931 (0x2E9B), caLm 4, HasCaDescriptors 1)
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: CAM error, try reset
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: close video input ...
Jun 29 12:54:09 vnas vdr[5799]: [14714] VNSI: activate live receiver: 0, pmt change: 0
Jun 29 12:54:10 vnas vdr[5799]: [14714] VNSI: Successfully found following device: 0x1c9bfc0 (4) for receiving
Jun 29 12:54:10 vnas vdr[5799]: [14714] VNSI: activate live receiver: 1, pmt change: 1
Jun 29 12:54:10 vnas vdr[5799]: [14714] DVBAPI: 3.0 set CAM decrypt (SID 11931 (0x2E9B), caLm 4, HasCaDescriptors 1)
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: CAM error, try reset
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: close video input ...
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: activate live receiver: 0, pmt change: 0
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: Successfully found following device: 0x1c9bfc0 (4) for receiving
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: activate live receiver: 1, pmt change: 1
Jun 29 12:54:12 vnas vdr[5799]: [14714] DVBAPI: 3.0 set CAM decrypt (SID 11931 (0x2E9B), caLm 4, HasCaDescriptors 1)
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: CAM error, try reset
Jun 29 12:54:12 vnas vdr[5799]: [14714] VNSI: close video input ...
[/code]

Anything else seams to work. Switching between crypted and non crypted channels works so far.
Only this channel seams to have an issue.

Thanks

**Comment by FernetMenta** [comment]
i recomment to disable scrample timeout. vdr detaches receivers after 3 secs ifpacktes are still scrambled. make no sense, in particular not for dvbapi

**Comment by FernetMenta** [comment]
see linked issue.

**Comment by FernetMenta** [comment]
please open another issue if there are still issues.
