### ISSUE TITLE
Compile error in vnsitimer.c

### ISSUE THREAD

**Issue by ralondo** [FernetMenta/vdr-plugin-vnsiserver#58]
When I try to compile, I get the follorwing error:

vnsitimer.c: In member function 'virtual void CVNSITimers::Action()':
vnsitimer.c:263:3: error: 'cStateKey' was not declared in this scope
   cStateKey timerState;
   ^
vnsitimer.c:263:13: error: expected ';' before 'timerState'
   cStateKey timerState;
             ^
vnsitimer.c:262:8: warning: unused variable 'modified' [-Wunused-variable]
   bool modified;
        ^
make: *** [vnsitimer.o] Error 1

What can I do?

**Comment by FernetMenta** [comment]
> What can I do?

fixed, rebase and it should work

**Comment by ralondo** [comment]
Perfect, thanks!
