### ISSUE TITLE
latest Git sometimes doesn't play sound

### ISSUE THREAD

**Issue by Karl-opec** [FernetMenta/vdr-plugin-vnsiserver#65]
With latest Git (7ee66aa) I observe sometimes, that the client does not play audio after channel switch. switching channels forward and back, audio is played then. It seams not related to scrambled or not scrambled

Any idea?

**Comment by FernetMenta** [comment]
please pastebin syslog and kodi debug log for such a case

**Comment by FernetMenta** [comment]
I think I found the issue. Should be fixed in master

**Comment by Karl-opec** [comment]
Great, Thanks. I will watch and report back when I observe it again.
