### ISSUE TITLE
lock sequence with vdr-2.3.6 is faulty

### ISSUE THREAD

**Issue by beinhart** [FernetMenta/vdr-plugin-vnsiserver#93]
see log from syslog

[lock_sequenze.txt](https://github.com/FernetMenta/vdr-plugin-vnsiserver/files/1065681/lock_sequenze.txt)

greetings
beinhart

**Comment by FernetMenta** [comment]
cool new feature of vdr 2.3.6 that it logs wrong locking.
thanks, I will look into this soon

**Comment by FernetMenta** [comment]
should be fixed by https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/2c42df3cf1ba37184e9106091f383ea6009490da
