### ISSUE TITLE
Protocol Version difference

### ISSUE THREAD

**Issue by Karl-opec** [FernetMenta/vdr-plugin-vnsiserver#98]
I run on my vdr server the latest vdr-plugin-vnsiserver from git

```initializing plugin: vnsiserver (1.5.2): VDR-Network-Streaming-Interface (VNSI) Server```

The client logs following connect message:

```
10:27:56.223 T:140550380447488  NOTICE: AddOnLog: VDR VNSI Client: Logged in at '1503476876+7200' to 'VDR-Network-Streaming-Interface (VNSI) Server' Version: '1.5.2' with protocol version '11'
 ```

The server logs:

```
Aug 23 10:27:56 vnas vdr[4568]: [2363] VNSI: Welcome client 'XBMC Media Center' with protocol version '10'
```

Is this (protocol 10 vs. 11) something to investigate? As i having a simular issue as described in Issue #97 "no data error with VNSI"

If I  can help further please advise.

**Comment by fsironman** [comment]
Can you further elaborate your Issues and Setup?

**Comment by FernetMenta** [comment]
vnsiserver is backwards compatible and allows older clients to connect. works as designed.

**Comment by Karl-opec** [comment]
so the client log line means the server supports proto 11 
and the server log line means it operates with client in proto  10?

My first understandings of these messages was different.

**Comment by FernetMenta** [comment]
yes
